version: "3.8"

services:
  frontend:
    build: ./example-frontend
    ports:
      - 5000:5000
  backend:
    build: ./example-backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis
    ports:
      - 6379:6379
    restart: unless-stopped
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - database:/var/lin/postgresql/data

volumes:
  database:
