version: "3.8"

services:
  frontend:
    build: ./example-frontend
    ports:
      - 5000:5000
    depends_on:
      - backend
  backend:
    build: ./example-backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=postgres
      - REQUEST_ORIGIN=http://localhost
    depends_on:
      - db
  redis:
    image: redis
    ports:
      - 6379:6379
    restart: unless-stopped
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database:/var/lib/postgresql/data
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend

volumes:
  db:
  nginx:
